format = """
$hostname$directory$c$python$java$lua$rust
$character
"""
right_format = "$git_branch$git_commit$git_state$git_status"

[hostname]
disabled = false
ssh_only = true
style = "bold #ff5f00"
format = "[$hostname]($style):"

[character]
success_symbol = "[â®‘](#aaaaaa) "
error_symbol = "[â®‘](#ed4747) "

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = false
read_only = " ï€£"
read_only_style = "#ed4747"
style = "blck"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_commit]
style = "#9274ed"
format = "[\\($hash$tag\\)]($style)"

[git_branch]
symbol = "î‚ "
style = "#aaaaaa"
format = "[$symbol$branch]($style)"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
style = "bold #9274ed"
format = "([\\[$all_status$ahead_behind\\]]($style))"

[python]
format = "via [$symbol$version]($style)"
symbol = "îˆµ "

[aws]
symbol = "îŒ½  "
format = "via [$symbol$version]($style)"

[buf]
symbol = "ï’ "
format = "via [$symbol$version]($style)"

[c]
symbol = "î˜ "
format = "via [$symbol$version]($style)"

[conda]
symbol = "ï„Œ "
format = "via [$symbol$version]($style)"

[dart]
symbol = "î˜ "
format = "via [$symbol$version]($style)"

[docker_context]
symbol = "ïŒˆ "
format = "via [$symbol$version]($style)"

[elixir]
symbol = "î‰µ "
format = "via [$symbol$version]($style)"

[elm]
symbol = "î˜¬ "
format = "via [$symbol$version]($style)"

[golang]
symbol = "î˜§ "
format = "via [$symbol$version]($style)"

[guix_shell]
symbol = "ïŒ¥ "
format = "via [$symbol$version]($style)"

[haskell]
symbol = "î· "
format = "via [$symbol$version]($style)"

[haxe]
symbol = "âŒ˜ "
format = "via [$symbol$version]($style)"

[hg_branch]
symbol = "ï˜ "
format = "via [$symbol$version]($style)"

[java]
symbol = "î‰– "
format = "via [$symbol$version]($style)"

[julia]
symbol = "î˜¤ "
format = "via [$symbol$version]($style)"

[lua]
symbol = "î˜  "
format = "via [$symbol$version]($style)"

[memory_usage]
symbol = "ï¡š "

[meson]
symbol = "ï¨¶ "
format = "via [$symbol$version]($style)"

[nim]
symbol = "ïš¤ "
format = "via [$symbol$version]($style)"

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "
format = "via [$symbol$version]($style)"

[rust]
symbol = "î¨ "
format = "via [$symbol$version]($style)"

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "
